apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::024579064366:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-VvtgyjAjMgh0
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::024579064366:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::024579064366:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::024579064366:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::024579064366:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::024579064366:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-VvtgyjAjMgh0\n  groups:\n  - system:bootstrappers\n  - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- groups:\n  - roboshop-trainee\n  userarn: arn:aws:iam::024579064366:user/suresh\n  username: suresh\n- groups:\n  - roboshop-admin\n  userarn: arn:aws:iam::024579064366:user/ramesh\n  username: ramesh\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-06-08T13:46:37Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"175471","uid":"b0749e37-c62c-41b5-8d45-c800d261c674"}}
  creationTimestamp: "2026-06-08T13:46:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "187171"
  uid: b0749e37-c62c-41b5-8d45-c800d261c674
